# fly.toml app configuration file generated for dot-country-indexer on 2024-01-15T21:32:31-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dot-country-indexer"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024
